# Generated by Django 5.2.10 on 2026-01-19 20:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_username_emailverificationtoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="full_name",
            field=models.CharField(
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Za-zА-Яа-яЁё\\s\\-]{2,100}$",
                        "Full name must be 2–100 characters and may contain only letters (Latin/Cyrillic), spaces, and hyphens.",
                    )
                ],
            ),
        ),
    ]
